#ifndef MESSAGEQUEUE_GLOBAL_H
#define MESSAGEQUEUE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MESSAGEQUEUE_LIBRARY)
#  define MESSAGEQUEUESHARED_EXPORT Q_DECL_EXPORT
#else
#  define MESSAGEQUEUESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MESSAGEQUEUE_GLOBAL_H
